# -*- coding: utf-8 -*-
"""guvi project 2 problem no.4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zrMIui34J7oQNd_wt3RpHIFBIpWaRw6_
"""

import matplotlib.pyplot as plt
import numpy as np

# Sample dataset
marks = [45, 56, 78, 88, 34, 60, 71, 49, 53, 67, 95, 100, 37, 43, 80]

# Define custom bins to match expected ranges
bins = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

counts, bin_edges, patches = plt.hist(
    marks,
    bins=bins,
    edgecolor='black',
    color='skyblue'
)

for count, edge in zip(counts, bin_edges):
    if count > 0:
        plt.text(edge + 2, count + 0.05, str(int(count)), ha='center', fontsize=9)

plt.xlabel("Marks Range")
plt.ylabel("Number of Students")
plt.title("Distribution of Student Marks")
plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.savefig("student_marks_histogram.png", dpi=300)

plt.show()

for i in range(len(bins)-1):
    print(f"{bins[i]+1 if i>0 else bins[i]}–{bins[i+1]}: {int(counts[i])} students")